### PR TITLE
Setting up - Closes #1

### LINKED ISSUE #1: See all reminders
- When the user visits the root of the application (e.g. the "/" URL), they should see a list of all of the reminders on the page.
- Each reminder should have a class of `.spec-reminder-item`.

There is a failing test set up in `tests/acceptance/reminder-list-test.js`.

**Hot Tip**: If you name your pull request or even your commit with "Closes #1", it will automatically close this issue when it successfully merged into master.

### PR DESCRIPTION
**Pull request by kylem038**
@stevekinney @tehviking

## Purpose

_Set up Remember App so that it shows the initial 5 reminders. Get the initial test passing._

## Approach

_This change allows the initial 5 reminders from the store to be rendered to the page. Before there was nothing rendering to the page._

### Learning

_Our initial pass at this revealed some of the inner workings of Ember, namely that it functions on the basis that our models must have corresponding routes in order to have those features function. I paired with Brandon & walked through setting up the index route within the router.js file. We also added the return statement to the route itself which connects it to the data store via context. Finally, I learned that when using a for loop with Ember it must refer to the word 'model' & not the name of the model file you're referring to._

_Links to blog posts, patterns, libraries or add-ons used to solve this problem._

### Open Questions and Pre-Merge TODOs

- [ ] Use Github checklists. When solved, check the box and explain the answer.

### Test coverage 

_We have not written any tests for this portion of the project._

### Merge Dependencies and Related Work

_Currently there are no merge dependencies._

### Follow-up tasks

- [Issue #2 (Example)](https://github.com/flexyford/pull-request/issues)

#### After
screen shot 2016-10-12 at 5 32 57 pm

### CODE REVIEW

File: app/controllers/reminders.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import Ember from 'ember';
+
+export default Ember.Controller.extend({
```
Comment (stevekinney) [inline app/controllers/reminders.js]: We don't need this file if it's not being used.

File: app/templates/reminders.hbs [hunk 2]
```diff
@@ -0,0 +1,13 @@
+<section class="application">
```
Comment (stevekinney) [inline app/templates/reminders.hbs]: If this `<section>` and the other ceremony around the list is classed with `.application` then it should be in the application template.

Comment (stevekinney) [inline app/templates/reminders.hbs]: If this `<section>` and the other ceremony around the list is classed with `.application` then it should be in the application template.

File: app/templates/reminders.hbs [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+  <header>
+    <h1>Reminders</h1>
+  </header>
+  {{#each model as |reminder|}}
+  <article class='spec-reminder-item'>
+    <h3>{{reminder.title}}</h3>
+    <h2>{{reminder.date}}</h2>
```
Comment (stevekinney) [inline app/templates/reminders.hbs]: The date really isn't a heading. I suspect you're using an `<h2>` to make it bigger. Consider using another tag and just giving it a class so that you can style it later.

File: app/templates/reminders.hbs (hunk 2 above)
Comment (kylem038) [inline app/templates/reminders.hbs]: Cool - I'm change the class name to '.reminder'.

**Comment by kylem038** [comment]
@stevekinney Thanks for the feedback! I believe it's all been addressed.
